/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;
import java.sql.*;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author aslam
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
        setLocationRelativeTo(null);
        Connect();
    }
    
    Connection con;
    PreparedStatement ps1;
    PreparedStatement ps2;
    
    public void Connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Students1","root","1234");
        
    }catch(Exception ex){
            System.out.println("Error in connection");
    }
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Book_Id = new javax.swing.JLabel();
        Book_Title = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        vBook_Id = new javax.swing.JTextField();
        vBook_Title = new javax.swing.JTextField();
        vAuthor = new javax.swing.JTextField();
        vPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Issued_date = new javax.swing.JLabel();
        vAvailableBook = new javax.swing.JButton();
        vIssued_Date = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Book_Id.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Book_Id.setText("Book Id:");
        getContentPane().add(Book_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 80, -1));

        Book_Title.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Book_Title.setText("Book Title:");
        getContentPane().add(Book_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        Price.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Price.setText("Price:");
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        Author.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Author.setText("Author:");
        getContentPane().add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        vBook_Id.setBackground(new java.awt.Color(255, 255, 153));
        vBook_Id.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        getContentPane().add(vBook_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 210, -1));

        vBook_Title.setBackground(new java.awt.Color(255, 255, 153));
        vBook_Title.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        getContentPane().add(vBook_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 210, -1));

        vAuthor.setBackground(new java.awt.Color(255, 255, 153));
        vAuthor.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        vAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(vAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 210, -1));

        vPrice.setBackground(new java.awt.Color(255, 255, 153));
        vPrice.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        getContentPane().add(vPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 210, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("ADD NEW BOOKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, 20));

        vSave.setBackground(new java.awt.Color(0, 102, 102));
        vSave.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        vSave.setForeground(new java.awt.Color(255, 255, 255));
        vSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/save-icon--1.png"))); // NOI18N
        vSave.setText("Save");
        vSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSaveActionPerformed(evt);
            }
        });
        getContentPane().add(vSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 130, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/back (1).png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 130, 40));

        Issued_date.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Issued_date.setText("Issued Date:");
        getContentPane().add(Issued_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        vAvailableBook.setBackground(new java.awt.Color(204, 255, 204));
        vAvailableBook.setFont(new java.awt.Font("Liberation Sans", 2, 10)); // NOI18N
        vAvailableBook.setForeground(new java.awt.Color(255, 51, 51));
        vAvailableBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/icons8-click-24.png"))); // NOI18N
        vAvailableBook.setText("Click here to watch avilable books");
        vAvailableBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vAvailableBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vAvailableBookActionPerformed(evt);
            }
        });
        getContentPane().add(vAvailableBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 230, 40));
        getContentPane().add(vIssued_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/123456.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vAuthorActionPerformed

    private void vSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSaveActionPerformed
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        
        try{
        int Book_Id=Integer.parseInt(vBook_Id.getText());
        String Book_Title=vBook_Title.getText();
        String Author=vAuthor.getText();
        int Price=Integer.parseInt(vPrice.getText());
        String Issued_Date=dFormat.format(vIssued_Date.getDate());
//        
        
        
        
        ps1 = con.prepareStatement("SELECT * FROM BookDetails WHERE Book_Id = ?");
        ps1.setInt(1, Book_Id);
        ResultSet resultSet = ps1.executeQuery();

        if (resultSet.next()) {
            JOptionPane.showMessageDialog(this, "Book with this ID already exists");
        } else {
            ps1 = con.prepareStatement("insert into BookDetails values(?,?,?,?,?)");

            ps1.setInt(1, Book_Id);
            ps1.setString(2, Book_Title);
            ps1.setString(3, Author);
            ps1.setString(4, Issued_Date);
            ps1.setDouble(5, Price);
            

            int Status = ps1.executeUpdate();
        if(Status==1){
            JOptionPane.showMessageDialog(this,"Added succusfully");
            vBook_Id.setText("");
            vBook_Title.setText("");
            vAuthor.setText("");
            vPrice.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this,"Oops, something went wrong");
        }
        
        }
        }catch(Exception Ex){
            System.out.println("Error in add book code");
        }
    }//GEN-LAST:event_vSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
//        Home1 hm=new Home1();
//        hm.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vAvailableBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vAvailableBookActionPerformed
        new AvailableBooks().setVisible(true);
        
    }//GEN-LAST:event_vAvailableBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Book_Id;
    private javax.swing.JLabel Book_Title;
    private javax.swing.JLabel Issued_date;
    private javax.swing.JLabel Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField vAuthor;
    private javax.swing.JButton vAvailableBook;
    private javax.swing.JTextField vBook_Id;
    private javax.swing.JTextField vBook_Title;
    private com.toedter.calendar.JDateChooser vIssued_Date;
    private javax.swing.JTextField vPrice;
    private javax.swing.JButton vSave;
    // End of variables declaration//GEN-END:variables
}
