/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import com.toedter.calendar.JDateChooser;
/**
 *
 * @author aslam
 */
public class Student1 extends javax.swing.JFrame {

    /**
     * Creates new form Student1
     */
    public Student1() {
        initComponents();
       //setExtendedState(JFrame.MAXIMIZED_BOTH);
       setLocationRelativeTo(null);
        Connect();
    }
    Connection con;
    PreparedStatement ps1;
    PreparedStatement ps2;
    PreparedStatement ps3;
    PreparedStatement ps4;
    PreparedStatement ps5;
    PreparedStatement ps6;
    
    public void Connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Students1","root","1234");
        
    }catch(Exception ex){
            System.out.println("Error in connection");
    }
        
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Student_Id = new javax.swing.JLabel();
        vStudent_Id = new javax.swing.JTextField();
        Student_Name = new javax.swing.JLabel();
        vStudent_Name = new javax.swing.JTextField();
        Student_Class = new javax.swing.JLabel();
        vClass = new javax.swing.JTextField();
        Contect_Num = new javax.swing.JLabel();
        vContect_Num = new javax.swing.JTextField();
        vSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        vDate = new com.toedter.calendar.JDateChooser();
        RegsDate = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Student_Id.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Student_Id.setText("Student Id:");
        getContentPane().add(Student_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, 24));

        vStudent_Id.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(vStudent_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 170, -1));

        Student_Name.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Student_Name.setText("Student Name:");
        getContentPane().add(Student_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        vStudent_Name.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(vStudent_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 170, -1));

        Student_Class.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Student_Class.setText("Class:");
        getContentPane().add(Student_Class, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        vClass.setBackground(new java.awt.Color(255, 255, 153));
        vClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vClassActionPerformed(evt);
            }
        });
        getContentPane().add(vClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 170, -1));

        Contect_Num.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Contect_Num.setText("Contect Num:");
        getContentPane().add(Contect_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        vContect_Num.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(vContect_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 170, -1));

        vSave.setBackground(new java.awt.Color(0, 102, 102));
        vSave.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        vSave.setForeground(new java.awt.Color(255, 255, 255));
        vSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/icons8-registration-32.png"))); // NOI18N
        vSave.setText("Register");
        vSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSaveActionPerformed(evt);
            }
        });
        getContentPane().add(vSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 130, 40));

        jLabel3.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("RAGISTER NEW STUDENTS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 250, 40));

        vDate.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(vDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, -1));

        RegsDate.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        RegsDate.setText("Reg.Date");
        getContentPane().add(RegsDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/back (1).png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/123456.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSaveActionPerformed
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
    
        try{
            String Student_Id=vStudent_Id.getText();
            String Student_Name=vStudent_Name.getText();
            String Student_Class=vClass.getText();
            int Contect_Num=Integer.parseInt(vContect_Num.getText());
            String RegsDate=dFormat.format(vDate.getDate());

        
        ps1=con.prepareStatement("insert into StudentsDetails values (?,?,?,?,?)");
        ps1.setString(1,Student_Id);
        ps1.setString(2,Student_Name);
        ps1.setString(3,Student_Class);
        ps1.setString(4, RegsDate);
        ps1.setInt(5,Contect_Num);
        
        
        
        int Status=ps1.executeUpdate();
        if(Status==1){
            JOptionPane.showMessageDialog(this, "Saved succusfully");
            vStudent_Id.setText("");
            vStudent_Name.setText("");
            vClass.setText("");
            vContect_Num.setText("");
            
        }else{
            JOptionPane.showMessageDialog(this, "Can't save");
        }
        
        
        }catch(Exception ex){
            System.out.println("Error in student details code");
        }    
    }//GEN-LAST:event_vSaveActionPerformed

    private void vClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vClassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
//        Home1 hm=new Home1();
//        hm.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contect_Num;
    private javax.swing.JLabel RegsDate;
    private javax.swing.JLabel Student_Class;
    private javax.swing.JLabel Student_Id;
    private javax.swing.JLabel Student_Name;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField vClass;
    private javax.swing.JTextField vContect_Num;
    private com.toedter.calendar.JDateChooser vDate;
    private javax.swing.JButton vSave;
    private javax.swing.JTextField vStudent_Id;
    private javax.swing.JTextField vStudent_Name;
    // End of variables declaration//GEN-END:variables
}
